// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_mensagens_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-D9_GrY9AEUUVbOYzEBA_FyemjnctkM',
    appId: '1:587027889252:web:1c1aa6ae37f5dd77de7371',
    messagingSenderId: '587027889252',
    projectId: 'agrogeo-brasil-app',
    authDomain: 'agrogeo-brasil-app.firebaseapp.com',
    storageBucket: 'agrogeo-brasil-app.firebasestorage.app',
    measurementId: 'G-C24QF9GZPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-NxqoEAHVSo8YA9ofPDBpSuVhUDKBAoY',
    appId: '1:587027889252:android:afe3873651cf28c4de7371',
    messagingSenderId: '587027889252',
    projectId: 'agrogeo-brasil-app',
    storageBucket: 'agrogeo-brasil-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQ9ZarOjW0IZ1cA1KPeeEHDXVn_c509A',
    appId: '1:587027889252:ios:f2eced38fa8c547bde7371',
    messagingSenderId: '587027889252',
    projectId: 'agrogeo-brasil-app',
    storageBucket: 'agrogeo-brasil-app.firebasestorage.app',
    iosBundleId: 'br.com.agrogeo.agrogeoBrasilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQ9ZarOjW0IZ1cA1KPeeEHDXVn_c509A',
    appId: '1:587027889252:ios:f2eced38fa8c547bde7371',
    messagingSenderId: '587027889252',
    projectId: 'agrogeo-brasil-app',
    storageBucket: 'agrogeo-brasil-app.firebasestorage.app',
    iosBundleId: 'br.com.agrogeo.agrogeoBrasilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm-D9_GrY9AEUUVbOYzEBA_FyemjnctkM',
    appId: '1:587027889252:web:effb81331cba3f43de7371',
    messagingSenderId: '587027889252',
    projectId: 'agrogeo-brasil-app',
    authDomain: 'agrogeo-brasil-app.firebaseapp.com',
    storageBucket: 'agrogeo-brasil-app.firebasestorage.app',
    measurementId: 'G-JLPEDMCSG9',
  );
}
