// File generated by Manus based on user-provided configs.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// IMPORTANT: This file assumes the correct Firebase project is 'painel-agrogeo'.
// The original iOS configurations were removed as they belonged to a different project ('agrogeo-brasil-app').
// You need to add an iOS app to the 'painel-agrogeo' project in the Firebase Console
// and then regenerate this file (e.g., using `flutterfire configure`) or manually add
// the correct iOS configurations if you intend to support iOS.

// ALSO IMPORTANT: Ensure `flutter pub get` runs successfully in your environment (FlutLab)
// to resolve the `firebase_core` import error before using this file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // TODO: Add correct iOS configurations from 'painel-agrogeo' project.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios for project painel-agrogeo - '
          'Add an iOS app to your Firebase project and configure it.',
        );
      case TargetPlatform.macOS:
        // TODO: Add correct macOS configurations if needed.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - ',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - ',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - ',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configs for Firebase project: painel-agrogeo
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6aXPBKbPV1qehRJCjffdUiIwfUpSLUg',
    appId: '1:213167893548:web:90aca852e1dbae3085f589',
    messagingSenderId: '213167893548',
    projectId: 'painel-agrogeo',
    authDomain: 'painel-agrogeo.firebaseapp.com',
    storageBucket:
        'painel-agrogeo.firebasestorage.app', // Corrigido para o domínio correto
    measurementId: 'G-RQFZXFEXD0',
  );

  // Configs for Firebase project: painel-agrogeo
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyDcw3K0YW8h9wRI7chfgdTczBRZ56T0q7M', // Key from google-services.json might differ from web key
    appId: '1:213167893548:android:b5b239eed68adea285f589',
    messagingSenderId: '213167893548',
    projectId: 'painel-agrogeo',
    storageBucket:
        'painel-agrogeo.firebasestorage.app', // Corrigido para o domínio correto
  );

  // iOS configurations removed as they belonged to a different project.
  // Add an iOS app to 'painel-agrogeo' and configure it here if needed.
  // static const FirebaseOptions ios = FirebaseOptions( ... );
}
